version: '3.9'
services:
  mysql:
    image: mysql:lastest
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DATABASE_ROOT_PASSWORD
      - MYSQL_USER=$DATABASE_USERNAME
      - MYSQL_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_DATABASE=$DATABASE_NAME
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - $DATABASE_HOST_PORT:$DATABASE_DOCKER_PORT
  api:
    build: ./Portfolio
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - $API_HOST_PORT:$API_DOCKER_PORT
    depends_on:
      mysql:
        condition: service_completed_successfully
    environment:
      - ConnectionSettings__Portfolio__ServerUrl=localhost
      - ConnectionSettings__Portfolio__ServerPort=$DATABASE_DOCKER_PORT
      - ConnectionSettings__Portfolio__DatabaseName=$DATABASE_NAME
      - ConnectionSettings__Portfolio__DatabaseUser=$DATABASE_USERNAME
      - ConnectionSettings__Portfolio__DatabasePassword=$DATABASE_PASSWORD
      - ConnectionSettings__ApiKey__ServerUrl=localhost
      - ConnectionSettings__ApiKey__ServerPort=$DATABASE_DOCKER_PORT
      - ConnectionSettings__ApiKey__DatabaseName=$DATABASE_NAME
      - ConnectionSettings__ApiKey__DatabaseUser=$DATABASE_USERNAME
      - ConnectionSettings__ApiKey__DatabasePassword=$DATABASE_PASSWORD
      - AdminKey=$API_ADMIN_KEY
    volumes:
      - static-files:./Portfolio/wwwroot
