version: '3.9'
services:
  mysql:
    image: mysql:latest
    restart: on-failure
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - ${DATABASE_HOST_PORT}:3306
  api:
    build:
      context: .
      dockerfile: ./Portfolio/Dockerfile
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - ${API_HOST_PORT}:80
    depends_on:
      mysql:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionSettings__Portfolio__ServerUrl=mysql
      - ConnectionSettings__Portfolio__ServerPort=3306
      - ConnectionSettings__Portfolio__DatabaseName=${DATABASE_NAME}
      - ConnectionSettings__Portfolio__DatabaseUser=root
      - ConnectionSettings__Portfolio__DatabasePassword=${DATABASE_PASSWORD}
      - ConnectionSettings__ApiKey__ServerUrl=mysql
      - ConnectionSettings__ApiKey__ServerPort=3306
      - ConnectionSettings__ApiKey__DatabaseName=${DATABASE_NAME}
      - ConnectionSettings__ApiKey__DatabaseUser=root
      - ConnectionSettings__ApiKey__DatabasePassword=${DATABASE_PASSWORD}
      - AdminKey=$API_ADMIN_KEY
    volumes:
      - ./static-files:/app/static-files
